#!/usr/bin/env python3
"""
Solar LSTM PV-per-kWp forecasting model (v3)

Purpose
-------
Use the same train/valid/test CSV files used for the wind experiments, but train a
solar-only model. The model predicts reference PV AC power per installed kWp:

    target_solar_power_kw_per_kwp  (preferred)
    or pv_ac_power_kw_per_kwp      (fallback)

The final prediction can be scaled to any reference PV scenario:

    reference_power_kw = predicted_kw_per_kwp * reference_capacity_kwp

Default reference capacity is 3370 kWp to match the 3.37 MW wind reference turbine
scenario used in the wind path.

Important leakage policy
------------------------
The script excludes direct PV output/energy/reference/hybrid target columns from the
input features. Solar-history features are generated with shift(1), so they use only
past target values.

Default feature_set='basic' avoids using PV intermediate columns such as
pv_poa_global_wm2 and pv_cell_temperature_c. You can enable them with
--feature_set physics if your experiment is intended as a PV-model emulator or a
NASA-aligned scenario that allows those derived physical inputs.

v3 addition
-----------
After training, the script fits small post-processing calibration options on the
validation split only, then applies the best option to the test split. This is
intended to reduce systematic positive bias without changing the trained model.
Available corrections include global, daylight/night, horizon-wise, and
horizon-wise daylight/night bias corrections.
"""

import os
import json
import copy
import argparse
import random
from typing import Dict, List, Optional, Sequence, Tuple

import joblib
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler


# ============================================================
# Reproducibility
# ============================================================


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


# ============================================================
# Columns and constants
# ============================================================

CITY_COL = "city_canonical"
RAW_CITY_COL = "city"
TIME_COL = "time"

PREFERRED_TARGET_COL = "target_solar_power_kw_per_kwp"
FALLBACK_TARGET_COL = "pv_ac_power_kw_per_kwp"
RAW_TARGET_COL = "actual_solar_kw_per_kwp"
TARGET_VALUE_COL = "target_solar_raw_kw_per_kwp"
TARGET_SCALED_COL = "target_solar_scaled"

DAYLIGHT_COL = "is_daylight"

DEFAULT_LOOKBACKS = [6, 24, 48, 72, 168]
DEFAULT_EMBEDDING_DIMS = [2, 4, 8]
DEFAULT_SEEDS = [1, 2, 3]

DEFAULT_REFERENCE_CAPACITY_KWP = 3370.0
DEFAULT_MAX_KW_PER_KWP = 1.20
DEFAULT_DAYLIGHT_WEIGHTS = [1.0, 2.0, 4.0]
DEFAULT_PRODUCTION_WEIGHTS = [0.5, 1.0]
DEFAULT_BIAS_CORRECTIONS = [
    "none",
    "global_bias",
    "daylight_bias",
    "horizon_bias",
    "horizon_daylight_bias",
]


# ============================================================
# Feature groups
# ============================================================

TIME_FEATURES = [
    "hour_sin", "hour_cos",
    "month_sin", "month_cos",
    "dayofyear_sin", "dayofyear_cos",
    "weekofyear_sin", "weekofyear_cos",
    "season_Winter", "season_Spring", "season_Summer", "season_Autumn",
    "is_daylight",
]

WEATHER_RADIATION_FEATURES = [
    "temperature_2m_c",
    "dew_point_2m_c",
    "relative_humidity_2m_pct",
    "surface_pressure_kpa",
    "precipitation_mm_per_hour",
    "cloud_cover_pct",
    "shortwave_radiation_ghi_wm2",
    "direct_normal_irradiance_dni_wm2",
    "diffuse_radiation_dhi_wm2",
    "clear_sky_ghi_wm2",
    "all_sky_clearness_index",
]

SOLAR_GEOMETRY_FEATURES = [
    "solar_zenith_deg",
    "solar_elevation_deg",
    "solar_azimuth_deg",
    "solar_cos_aoi",
]

STATIC_LOCATION_FEATURES = [
    "city_latitude_deg",
    "city_longitude_deg",
    "solar_latitude_deg",
    "solar_longitude_deg",
    "pv_tilt_deg",
    "pv_azimuth_deg",
]

# Optional physical/intermediate PV columns. Use only with --feature_set physics.
PV_PHYSICS_FEATURES = [
    "pv_poa_global_wm2",
    "pv_cell_temperature_c",
]

# Generated by add_ar_solar_features(). All are past-only.
SOLAR_AR_FEATURES = [
    "solar_lag1",
    "solar_lag2",
    "solar_lag3",
    "solar_lag6",
    "solar_lag12",
    "solar_lag24",
    "solar_lag48",
    "solar_lag168",
    "solar_roll3_mean",
    "solar_roll6_mean",
    "solar_roll12_mean",
    "solar_roll24_mean",
    "solar_roll3_std",
    "solar_roll6_std",
    "solar_roll12_std",
    "solar_delta1",
    "solar_delta2",
    "solar_delta3",
    "solar_daylight_lag1",
]

# Direct targets, generated PV outputs, reference/hybrid outputs, and wind outputs.
# These are not allowed as model features.
LEAKAGE_OR_NON_SOLAR_FEATURES = {
    "target",
    "target_wind_power_kw",
    "target_solar_power_kw_per_kwp",
    "target_solar_reference_power_kw",
    "target_hybrid_power_kw",
    "wind_gross_power_kw",
    "wind_gross_energy_kwh",
    "wind_gross_capacity_factor",
    "wind_normalized_power",
    "diagnostic_wind_aero_power_kw",
    "pv_dc_power_kw_per_kwp",
    "pv_ac_power_kw_per_kwp",
    "pv_energy_kwh_per_kwp",
    "pv_capacity_factor_dc",
    "pv_capacity_factor_ac",
    "pv_normalized_power",
    "pv_reference_power_kw",
    "pv_reference_energy_kwh",
    "pv_reference_capacity_factor",
    "hybrid_reference_power_kw",
    "hybrid_reference_energy_kwh",
    "hybrid_reference_capacity_kw",
    "hybrid_reference_capacity_factor",
    "hybrid_normalized_power",
    "wind_minus_pv_normalized",
    "abs_wind_minus_pv_normalized",
    "wind_pv_product_normalized",
    "hybrid_power_24h_mean_kw",
    "hybrid_power_24h_std_kw",
    RAW_TARGET_COL,
    TARGET_VALUE_COL,
    TARGET_SCALED_COL,
}

BINARY_COLS = {
    "is_daylight", "complete_expected_period",
    "pv_low_flag", "pv_high_flag",
    "wind_low_flag", "both_low_flag", "wind_high_flag",
    "wind_high_solar_low_flag", "solar_high_wind_low_flag", "both_high_flag",
    "season_Winter", "season_Spring", "season_Summer", "season_Autumn",
}

METADATA_COLS = {
    "time", "city", "city_canonical",
    "source_file_tag", "source_file_path", "dataset_split", "season",
}


# ============================================================
# Helpers
# ============================================================


def available_only(cols: Sequence[str], available_cols: Sequence[str]) -> List[str]:
    available = set(available_cols)
    return [c for c in cols if c in available]


def float_tag(value: float) -> str:
    """Make a filesystem-safe compact tag for float hyperparameters."""
    text = f"{float(value):g}"
    return text.replace("-", "m").replace(".", "p")


def is_no_scale_column(col: str) -> bool:
    if col in BINARY_COLS:
        return True
    if "_sin" in col or "_cos" in col:
        return True
    if col == "city_id":
        return True
    return False


def resolve_target_col(df: pd.DataFrame, requested: str) -> str:
    requested = requested.strip()
    if requested.lower() != "auto":
        if requested not in df.columns:
            raise ValueError(f"Requested target column not found: {requested}")
        return requested

    if PREFERRED_TARGET_COL in df.columns:
        return PREFERRED_TARGET_COL
    if FALLBACK_TARGET_COL in df.columns:
        return FALLBACK_TARGET_COL
    raise ValueError(
        f"No solar target found. Expected {PREFERRED_TARGET_COL!r} or {FALLBACK_TARGET_COL!r}."
    )


def build_feature_columns(
    df: pd.DataFrame,
    feature_set: str,
    use_solar_history: bool,
) -> Tuple[List[str], List[str]]:
    feature_set = feature_set.lower().strip()

    candidates = (
        TIME_FEATURES
        + WEATHER_RADIATION_FEATURES
        + SOLAR_GEOMETRY_FEATURES
        + STATIC_LOCATION_FEATURES
    )

    if use_solar_history:
        candidates += SOLAR_AR_FEATURES

    if feature_set == "basic":
        pass
    elif feature_set == "physics":
        candidates += PV_PHYSICS_FEATURES
    else:
        raise ValueError("feature_set must be 'basic' or 'physics'.")

    feature_cols = available_only(candidates, df.columns)
    feature_cols = list(dict.fromkeys(feature_cols))

    feature_cols = [
        c for c in feature_cols
        if c not in METADATA_COLS and c not in LEAKAGE_OR_NON_SOLAR_FEATURES
    ]

    if not feature_cols:
        raise ValueError("No feature columns selected.")

    non_numeric = [c for c in feature_cols if not pd.api.types.is_numeric_dtype(df[c])]
    if non_numeric:
        raise ValueError(f"Non-numeric features selected: {non_numeric}")

    continuous_cols = [c for c in feature_cols if not is_no_scale_column(c)]
    return feature_cols, continuous_cols


# ============================================================
# Data loading
# ============================================================


def load_split(path: str, split_name: str, target_col_arg: str) -> Tuple[pd.DataFrame, str]:
    df = pd.read_csv(path)

    if TIME_COL not in df.columns:
        raise ValueError(f"{split_name}: missing column {TIME_COL}")

    if CITY_COL not in df.columns:
        if RAW_CITY_COL in df.columns:
            df[CITY_COL] = df[RAW_CITY_COL].astype(str).str.strip()
        else:
            raise ValueError(f"{split_name}: missing column {CITY_COL}")

    target_col = resolve_target_col(df, target_col_arg)

    df[TIME_COL] = pd.to_datetime(df[TIME_COL], errors="coerce", utc=True)
    df[CITY_COL] = df[CITY_COL].astype(str).str.strip()
    df[target_col] = pd.to_numeric(df[target_col], errors="coerce")

    if DAYLIGHT_COL in df.columns:
        df[DAYLIGHT_COL] = pd.to_numeric(df[DAYLIGHT_COL], errors="coerce").fillna(0).astype(int)
    else:
        df[DAYLIGHT_COL] = (df[target_col].fillna(0) > 0).astype(int)

    df = df.dropna(subset=[TIME_COL, CITY_COL, target_col]).copy()

    if "city_id" not in df.columns:
        city_vocab = {city: idx for idx, city in enumerate(sorted(df[CITY_COL].unique()))}
        df["city_id"] = df[CITY_COL].map(city_vocab).astype(int)

    df = df.sort_values([CITY_COL, TIME_COL]).reset_index(drop=True)
    return df, target_col


def check_split_integrity(train_df: pd.DataFrame, val_df: pd.DataFrame, test_df: pd.DataFrame) -> None:
    train_cities = sorted(train_df[CITY_COL].unique().tolist())
    val_cities = sorted(val_df[CITY_COL].unique().tolist())
    test_cities = sorted(test_df[CITY_COL].unique().tolist())

    if not (train_cities == val_cities == test_cities):
        raise ValueError(
            f"City mismatch.\nTrain: {train_cities}\nValid: {val_cities}\nTest: {test_cities}"
        )

    for name, df in [("train", train_df), ("valid", val_df), ("test", test_df)]:
        dups = int(df.duplicated(subset=[CITY_COL, TIME_COL]).sum())
        if dups > 0:
            raise ValueError(f"{name}: {dups} duplicated city-time rows.")

    print("Split integrity check: PASSED")
    print(f"Cities : {train_cities}")
    print(f"Rows   : train={len(train_df):,}  valid={len(val_df):,}  test={len(test_df):,}")


def prepare_physical_target(df: pd.DataFrame, target_col: str) -> pd.DataFrame:
    df = df.copy()
    df[RAW_TARGET_COL] = pd.to_numeric(df[target_col], errors="coerce")
    df[TARGET_VALUE_COL] = df[RAW_TARGET_COL].astype(float)
    df = df.dropna(subset=[RAW_TARGET_COL, TARGET_VALUE_COL]).copy()
    return df


def add_ar_solar_features(df: pd.DataFrame, target_col: str) -> pd.DataFrame:
    """Add lag/rolling/delta solar features, using only past values within each city."""
    df = df.copy()

    for _, g in df.groupby(CITY_COL, sort=True):
        idx = g.sort_values(TIME_COL).index
        y = df.loc[idx, target_col].astype(float)
        daylight = df.loc[idx, DAYLIGHT_COL].astype(float) if DAYLIGHT_COL in df.columns else (y > 0).astype(float)

        df.loc[idx, "solar_lag1"] = y.shift(1)
        df.loc[idx, "solar_lag2"] = y.shift(2)
        df.loc[idx, "solar_lag3"] = y.shift(3)
        df.loc[idx, "solar_lag6"] = y.shift(6)
        df.loc[idx, "solar_lag12"] = y.shift(12)
        df.loc[idx, "solar_lag24"] = y.shift(24)
        df.loc[idx, "solar_lag48"] = y.shift(48)
        df.loc[idx, "solar_lag168"] = y.shift(168)

        df.loc[idx, "solar_roll3_mean"] = y.shift(1).rolling(3, min_periods=1).mean()
        df.loc[idx, "solar_roll6_mean"] = y.shift(1).rolling(6, min_periods=1).mean()
        df.loc[idx, "solar_roll12_mean"] = y.shift(1).rolling(12, min_periods=1).mean()
        df.loc[idx, "solar_roll24_mean"] = y.shift(1).rolling(24, min_periods=1).mean()

        df.loc[idx, "solar_roll3_std"] = y.shift(1).rolling(3, min_periods=2).std().fillna(0.0)
        df.loc[idx, "solar_roll6_std"] = y.shift(1).rolling(6, min_periods=2).std().fillna(0.0)
        df.loc[idx, "solar_roll12_std"] = y.shift(1).rolling(12, min_periods=2).std().fillna(0.0)

        df.loc[idx, "solar_delta1"] = y.shift(1) - y.shift(2)
        df.loc[idx, "solar_delta2"] = y.shift(2) - y.shift(3)
        df.loc[idx, "solar_delta3"] = y.shift(3) - y.shift(4)

        df.loc[idx, "solar_daylight_lag1"] = daylight.shift(1)

    return df


# ============================================================
# Scaling
# ============================================================


def fit_apply_scalers(
    train_df: pd.DataFrame,
    val_df: pd.DataFrame,
    test_df: pd.DataFrame,
    feature_cols: Sequence[str],
    continuous_cols: Sequence[str],
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, Optional[StandardScaler], StandardScaler]:
    train_df = train_df.copy()
    val_df = val_df.copy()
    test_df = test_df.copy()

    x_scaler = None
    if continuous_cols:
        x_scaler = StandardScaler()
        train_df[list(continuous_cols)] = x_scaler.fit_transform(
            train_df[list(continuous_cols)].to_numpy(dtype=np.float32)
        )
        val_df[list(continuous_cols)] = x_scaler.transform(
            val_df[list(continuous_cols)].to_numpy(dtype=np.float32)
        )
        test_df[list(continuous_cols)] = x_scaler.transform(
            test_df[list(continuous_cols)].to_numpy(dtype=np.float32)
        )

    y_scaler = StandardScaler()
    train_df[[TARGET_SCALED_COL]] = y_scaler.fit_transform(
        train_df[[TARGET_VALUE_COL]].to_numpy(dtype=np.float32)
    )
    val_df[[TARGET_SCALED_COL]] = y_scaler.transform(
        val_df[[TARGET_VALUE_COL]].to_numpy(dtype=np.float32)
    )
    test_df[[TARGET_SCALED_COL]] = y_scaler.transform(
        test_df[[TARGET_VALUE_COL]].to_numpy(dtype=np.float32)
    )

    for name, df in [("train", train_df), ("valid", val_df), ("test", test_df)]:
        if not np.isfinite(df[list(feature_cols)].to_numpy(dtype=np.float32)).all():
            raise ValueError(f"{name}: non-finite features after scaling.")
        if not np.isfinite(df[TARGET_SCALED_COL].to_numpy(dtype=np.float32)).all():
            raise ValueError(f"{name}: non-finite target after scaling.")

    return train_df, val_df, test_df, x_scaler, y_scaler


# ============================================================
# Dataset
# ============================================================


class SolarPVPerKwpDataset(Dataset):
    def __init__(
        self,
        df: pd.DataFrame,
        feature_cols: Sequence[str],
        lookback: int,
        horizon: int,
        use_city_embedding: bool,
    ):
        self.feature_cols = list(feature_cols)
        self.lookback = int(lookback)
        self.horizon = int(horizon)
        self.use_city_embedding = bool(use_city_embedding)

        self.x_by_city: List[np.ndarray] = []
        self.y_scaled_by_city: List[np.ndarray] = []
        self.y_raw_by_city: List[np.ndarray] = []
        self.daylight_by_city: List[np.ndarray] = []
        self.city_id_by_city: List[int] = []
        self.index_map: List[Tuple[int, int]] = []

        for _, g in df.groupby(CITY_COL, sort=False):
            g = g.sort_values(TIME_COL).reset_index(drop=True)

            x = np.ascontiguousarray(g[self.feature_cols].to_numpy(dtype=np.float32)).copy()
            y_scaled = np.ascontiguousarray(g[TARGET_SCALED_COL].to_numpy(dtype=np.float32)).copy()
            y_raw = np.ascontiguousarray(g[TARGET_VALUE_COL].to_numpy(dtype=np.float32)).copy()
            daylight = np.ascontiguousarray(g[DAYLIGHT_COL].to_numpy(dtype=np.float32)).copy()
            city_id = int(g["city_id"].iloc[0])

            city_idx = len(self.x_by_city)
            self.x_by_city.append(x)
            self.y_scaled_by_city.append(y_scaled)
            self.y_raw_by_city.append(y_raw)
            self.daylight_by_city.append(daylight)
            self.city_id_by_city.append(city_id)

            n = len(g)
            for t in range(self.lookback, n - self.horizon + 1):
                self.index_map.append((city_idx, t))

    def __len__(self) -> int:
        return len(self.index_map)

    def __getitem__(self, idx: int):
        city_idx, t = self.index_map[idx]

        x = self.x_by_city[city_idx][t - self.lookback: t].copy()
        y_scaled = self.y_scaled_by_city[city_idx][t: t + self.horizon].copy()
        y_raw = self.y_raw_by_city[city_idx][t: t + self.horizon].copy()
        daylight = self.daylight_by_city[city_idx][t: t + self.horizon].copy()
        city_id = self.city_id_by_city[city_idx]

        if self.use_city_embedding:
            return (
                torch.from_numpy(x),
                torch.tensor(city_id, dtype=torch.long),
                torch.from_numpy(y_scaled),
                torch.from_numpy(y_raw),
                torch.from_numpy(daylight),
            )

        return (
            torch.from_numpy(x),
            torch.from_numpy(y_scaled),
            torch.from_numpy(y_raw),
            torch.from_numpy(daylight),
        )


def unpack_batch(batch, use_city_embedding: bool):
    if use_city_embedding:
        x, city_id, y_scaled, y_raw, daylight = batch
        return x, city_id, y_scaled, y_raw, daylight
    x, y_scaled, y_raw, daylight = batch
    return x, None, y_scaled, y_raw, daylight


# ============================================================
# Models
# ============================================================


class SolarLSTM(nn.Module):
    def __init__(
        self,
        n_features: int,
        hidden_size: int,
        num_layers: int,
        dropout: float,
        horizon: int,
        head_hidden: int,
    ):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=n_features,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head = nn.Sequential(
            nn.Linear(hidden_size, head_hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(head_hidden, max(1, head_hidden // 2)),
            nn.ReLU(),
            nn.Dropout(dropout * 0.5),
            nn.Linear(max(1, head_hidden // 2), horizon),
        )

    def forward(self, x: torch.Tensor, city_id=None) -> torch.Tensor:
        out, _ = self.lstm(x)
        last = out[:, -1, :]
        return self.head(last)


class SolarLSTMCityEmbedding(nn.Module):
    def __init__(
        self,
        n_features: int,
        n_cities: int,
        city_embedding_dim: int,
        hidden_size: int,
        num_layers: int,
        dropout: float,
        horizon: int,
        head_hidden: int,
    ):
        super().__init__()
        self.embedding = nn.Embedding(n_cities, city_embedding_dim)
        self.lstm = nn.LSTM(
            input_size=n_features,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head = nn.Sequential(
            nn.Linear(hidden_size + city_embedding_dim, head_hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(head_hidden, max(1, head_hidden // 2)),
            nn.ReLU(),
            nn.Dropout(dropout * 0.5),
            nn.Linear(max(1, head_hidden // 2), horizon),
        )

    def forward(self, x: torch.Tensor, city_id: torch.Tensor) -> torch.Tensor:
        out, _ = self.lstm(x)
        last = out[:, -1, :]
        emb = self.embedding(city_id)
        z = torch.cat([last, emb], dim=1)
        return self.head(z)


# ============================================================
# Loss and metrics
# ============================================================


def build_horizon_weights(horizon: int, device: str) -> torch.Tensor:
    weights = torch.linspace(1.0, 1.5, horizon, device=device)
    return weights / weights.mean()


def elementwise_base_loss(pred: torch.Tensor, true: torch.Tensor, loss_name: str, huber_beta: float) -> torch.Tensor:
    loss_name = loss_name.lower()
    if loss_name == "mse":
        return (pred - true) ** 2
    if loss_name == "mae":
        return torch.abs(pred - true)
    if loss_name == "huber":
        diff = torch.abs(pred - true)
        beta = float(huber_beta)
        return torch.where(diff < beta, 0.5 * diff ** 2 / beta, diff - 0.5 * beta)
    raise ValueError("loss must be mse, mae, or huber")


def solar_weighted_loss(
    pred_scaled: torch.Tensor,
    true_scaled: torch.Tensor,
    true_raw: torch.Tensor,
    daylight: torch.Tensor,
    horizon_weights: torch.Tensor,
    loss_name: str,
    huber_beta: float,
    daylight_weight: float,
    night_weight: float,
    production_weight: float,
    max_kw_per_kwp: float,
) -> torch.Tensor:
    """
    Daylight-focused weighted loss.

    v2 change from v1:
    - daylight hours get an explicit weight;
    - night hours can be down-weighted so night zeros do not dominate;
    - higher-production hours get extra weight;
    - horizon weights are kept;
    - the final loss is normalized by the sum of weights so the scale remains stable
      when trying different daylight/production weights.
    """
    base = elementwise_base_loss(pred_scaled, true_scaled, loss_name, huber_beta)

    day = (daylight > 0.5).float()
    day_w = day * float(daylight_weight) + (1.0 - day) * float(night_weight)

    denom = max(float(max_kw_per_kwp), 1e-6)
    prod = torch.clamp(true_raw / denom, min=0.0, max=1.5)
    prod_w = 1.0 + float(production_weight) * prod

    h_w = horizon_weights.unsqueeze(0)
    weights = day_w * prod_w * h_w

    weighted = base * weights
    return weighted.sum() / torch.clamp(weights.sum(), min=1.0)


def inverse_scaled(arr: np.ndarray, scaler: StandardScaler) -> np.ndarray:
    shape = arr.shape
    inv = scaler.inverse_transform(arr.reshape(-1, 1))
    return inv.reshape(shape)


def compute_regression_metrics(pred: np.ndarray, true: np.ndarray, prefix: str = "") -> Dict[str, float]:
    pred_flat = pred.reshape(-1).astype(float)
    true_flat = true.reshape(-1).astype(float)
    diff = pred_flat - true_flat

    mae = float(np.mean(np.abs(diff)))
    rmse = float(np.sqrt(np.mean(diff ** 2)))
    denom = float(np.sum((true_flat - np.mean(true_flat)) ** 2))
    r2 = float("nan") if denom <= 0 else float(1.0 - np.sum(diff ** 2) / denom)

    return {
        f"{prefix}mae": mae,
        f"{prefix}rmse": rmse,
        f"{prefix}r2": r2,
        f"{prefix}bias": float(np.mean(diff)),
        f"{prefix}mean_true": float(np.mean(true_flat)),
        f"{prefix}mean_pred": float(np.mean(pred_flat)),
        f"{prefix}count": int(pred_flat.size),
    }


def compute_all_metrics(
    pred_per_kwp: np.ndarray,
    true_per_kwp: np.ndarray,
    daylight: Optional[np.ndarray],
    reference_capacity_kwp: float,
) -> Dict[str, float]:
    out: Dict[str, float] = {}

    out.update(compute_regression_metrics(pred_per_kwp, true_per_kwp, prefix="per_kwp_"))

    pred_ref_kw = pred_per_kwp * float(reference_capacity_kwp)
    true_ref_kw = true_per_kwp * float(reference_capacity_kwp)
    out.update(compute_regression_metrics(pred_ref_kw, true_ref_kw, prefix="reference_kw_"))

    # Percent-of-reference-capacity metrics. Since target is kW/kWp, this is numerically percent of capacity.
    diff_per_kwp = (pred_per_kwp.reshape(-1) - true_per_kwp.reshape(-1)).astype(float)
    out["mae_pct_of_reference_capacity"] = float(np.mean(np.abs(diff_per_kwp)) * 100.0)
    out["rmse_pct_of_reference_capacity"] = float(np.sqrt(np.mean(diff_per_kwp ** 2)) * 100.0)
    out["bias_pct_of_reference_capacity"] = float(np.mean(diff_per_kwp) * 100.0)

    out["mean_true_capacity_factor_pct"] = float(np.mean(true_per_kwp.reshape(-1)) * 100.0)
    out["mean_pred_capacity_factor_pct"] = float(np.mean(pred_per_kwp.reshape(-1)) * 100.0)

    if daylight is not None:
        mask = daylight.reshape(-1).astype(bool)
        if mask.any():
            out.update(
                compute_regression_metrics(
                    pred_per_kwp.reshape(-1)[mask],
                    true_per_kwp.reshape(-1)[mask],
                    prefix="daylight_per_kwp_",
                )
            )
            day_diff = diff_per_kwp[mask]
            out["daylight_rmse_pct_of_reference_capacity"] = float(np.sqrt(np.mean(day_diff ** 2)) * 100.0)
            out["daylight_mae_pct_of_reference_capacity"] = float(np.mean(np.abs(day_diff)) * 100.0)

    return out


# ============================================================
# Validation-fitted post-processing bias correction (v3)
# ============================================================


def final_physical_postprocess(
    pred_per_kwp: np.ndarray,
    daylight: np.ndarray,
    clip_per_kwp: bool,
    max_kw_per_kwp: float,
    force_night_zero: bool,
) -> np.ndarray:
    """Apply the same physical output constraints used in evaluation."""
    pred = np.asarray(pred_per_kwp, dtype=np.float32).copy()
    day = np.asarray(daylight, dtype=np.float32)
    if force_night_zero:
        pred = np.where(day > 0.5, pred, 0.0)
    if clip_per_kwp:
        pred = np.clip(pred, 0.0, float(max_kw_per_kwp))
    return pred.astype(np.float32)


def fit_bias_correction_params(
    pred_per_kwp: np.ndarray,
    true_per_kwp: np.ndarray,
    daylight: np.ndarray,
    method: str,
) -> Dict[str, object]:
    """
    Fit a tiny calibration layer on validation predictions only.

    Convention:
      error = pred - true
      corrected = pred - fitted_error

    This is intentionally simple and transparent. It is not a second model.
    """
    method = str(method).lower().strip()
    pred = np.asarray(pred_per_kwp, dtype=np.float64)
    true = np.asarray(true_per_kwp, dtype=np.float64)
    day = np.asarray(daylight, dtype=np.float64) > 0.5
    err = pred - true

    if method == "none":
        return {"method": "none"}

    if method == "global_bias":
        return {
            "method": method,
            "global_bias": float(np.nanmean(err)),
        }

    if method == "daylight_bias":
        global_bias = float(np.nanmean(err))
        day_bias = float(np.nanmean(err[day])) if np.any(day) else global_bias
        night_bias = float(np.nanmean(err[~day])) if np.any(~day) else global_bias
        return {
            "method": method,
            "global_bias": global_bias,
            "daylight_bias": day_bias,
            "night_bias": night_bias,
        }

    if method == "horizon_bias":
        h_bias = np.nanmean(err, axis=0).astype(float)
        return {
            "method": method,
            "horizon_bias": h_bias.tolist(),
            "global_bias": float(np.nanmean(err)),
        }

    if method == "horizon_daylight_bias":
        horizon = err.shape[1]
        global_bias = float(np.nanmean(err))
        h_day = np.zeros(horizon, dtype=float)
        h_night = np.zeros(horizon, dtype=float)
        h_all = np.nanmean(err, axis=0).astype(float)
        for h in range(horizon):
            m_day = day[:, h]
            m_night = ~m_day
            h_day[h] = float(np.nanmean(err[m_day, h])) if np.any(m_day) else float(h_all[h])
            h_night[h] = float(np.nanmean(err[m_night, h])) if np.any(m_night) else float(h_all[h])
        return {
            "method": method,
            "global_bias": global_bias,
            "horizon_bias": h_all.tolist(),
            "horizon_daylight_bias": h_day.tolist(),
            "horizon_night_bias": h_night.tolist(),
        }

    if method == "linear":
        x = pred.reshape(-1)
        y = true.reshape(-1)
        mask = np.isfinite(x) & np.isfinite(y)
        if mask.sum() < 2 or float(np.var(x[mask])) <= 1e-12:
            slope, intercept = 1.0, -float(np.nanmean(err))
        else:
            slope, intercept = np.polyfit(x[mask], y[mask], deg=1)
            slope = float(np.clip(slope, 0.50, 1.50))
            intercept = float(intercept)
        return {
            "method": method,
            "linear_slope": slope,
            "linear_intercept": intercept,
        }

    raise ValueError(
        f"Unknown bias correction method: {method}. "
        "Allowed: none, global_bias, daylight_bias, horizon_bias, horizon_daylight_bias, linear"
    )


def apply_bias_correction(
    pred_per_kwp: np.ndarray,
    daylight: np.ndarray,
    params: Dict[str, object],
) -> np.ndarray:
    method = str(params.get("method", "none")).lower().strip()
    pred = np.asarray(pred_per_kwp, dtype=np.float64).copy()
    day = np.asarray(daylight, dtype=np.float64) > 0.5

    if method == "none":
        return pred.astype(np.float32)

    if method == "global_bias":
        return (pred - float(params["global_bias"])).astype(np.float32)

    if method == "daylight_bias":
        corrected = pred.copy()
        corrected[day] -= float(params["daylight_bias"])
        corrected[~day] -= float(params["night_bias"])
        return corrected.astype(np.float32)

    if method == "horizon_bias":
        h_bias = np.asarray(params["horizon_bias"], dtype=np.float64).reshape(1, -1)
        return (pred - h_bias).astype(np.float32)

    if method == "horizon_daylight_bias":
        h_day = np.asarray(params["horizon_daylight_bias"], dtype=np.float64).reshape(1, -1)
        h_night = np.asarray(params["horizon_night_bias"], dtype=np.float64).reshape(1, -1)
        bias = np.where(day, h_day, h_night)
        return (pred - bias).astype(np.float32)

    if method == "linear":
        slope = float(params["linear_slope"])
        intercept = float(params["linear_intercept"])
        return (slope * pred + intercept).astype(np.float32)

    raise ValueError(f"Unknown correction method in params: {method}")


def get_metric_for_selection(metrics: Dict[str, float], metric_name: str) -> float:
    metric_name = str(metric_name)
    if metric_name == "abs_bias_pct_of_reference_capacity":
        return abs(float(metrics.get("bias_pct_of_reference_capacity", float("inf"))))
    if metric_name not in metrics:
        raise ValueError(f"Calibration metric not available: {metric_name}")
    return float(metrics[metric_name])


def choose_validation_correction(
    val_pred: np.ndarray,
    val_true: np.ndarray,
    val_daylight: np.ndarray,
    correction_methods: Sequence[str],
    selection_metric: str,
    reference_capacity_kwp: float,
    clip_per_kwp: bool,
    max_kw_per_kwp: float,
    force_night_zero: bool,
) -> Tuple[Dict[str, object], pd.DataFrame]:
    rows = []
    best_params: Optional[Dict[str, object]] = None
    best_score = float("inf")

    for method in correction_methods:
        params = fit_bias_correction_params(val_pred, val_true, val_daylight, method)
        corrected = apply_bias_correction(val_pred, val_daylight, params)
        corrected = final_physical_postprocess(
            corrected,
            val_daylight,
            clip_per_kwp=clip_per_kwp,
            max_kw_per_kwp=max_kw_per_kwp,
            force_night_zero=force_night_zero,
        )
        metrics = compute_all_metrics(corrected, val_true, val_daylight, reference_capacity_kwp)
        score = get_metric_for_selection(metrics, selection_metric)
        row = {
            "correction_method": method,
            "selection_metric": selection_metric,
            "selection_score": score,
            **{f"val_{k}": v for k, v in metrics.items()},
        }
        # Keep common scalar correction parameters readable in CSV.
        for key in ["global_bias", "daylight_bias", "night_bias", "linear_slope", "linear_intercept"]:
            if key in params:
                row[key] = params[key]
        rows.append(row)
        if score < best_score:
            best_score = score
            best_params = params

    if best_params is None:
        best_params = {"method": "none"}

    return best_params, pd.DataFrame(rows).sort_values("selection_score").reset_index(drop=True)


def per_horizon_metrics(
    pred_per_kwp: np.ndarray,
    true_per_kwp: np.ndarray,
    daylight: np.ndarray,
    reference_capacity_kwp: float,
) -> pd.DataFrame:
    rows = []
    for h in range(pred_per_kwp.shape[1]):
        metrics = compute_all_metrics(
            pred_per_kwp[:, h:h + 1],
            true_per_kwp[:, h:h + 1],
            daylight[:, h:h + 1],
            reference_capacity_kwp,
        )
        rows.append({"horizon_step": h + 1, **metrics})
    return pd.DataFrame(rows)


# ============================================================
# Training helpers
# ============================================================


class EarlyStopping:
    def __init__(self, patience: int, min_delta: float):
        self.patience = int(patience)
        self.min_delta = float(min_delta)
        self.best = float("inf")
        self.bad_epochs = 0

    def step(self, value: float) -> Tuple[bool, bool]:
        improved = (self.best - value) > self.min_delta
        if improved:
            self.best = value
            self.bad_epochs = 0
            return False, True
        self.bad_epochs += 1
        return self.bad_epochs >= self.patience, False


def make_loader(ds: Dataset, args, shuffle: bool, device: str) -> DataLoader:
    return DataLoader(
        ds,
        batch_size=args.batch_size,
        shuffle=shuffle,
        num_workers=args.num_workers,
        pin_memory=(device == "cuda"),
        drop_last=False,
    )


def count_windows(df: pd.DataFrame, lookback: int, horizon: int) -> pd.DataFrame:
    rows = []
    for city, g in df.groupby(CITY_COL, sort=False):
        n = len(g)
        rows.append({
            "city": city,
            "rows": int(n),
            "windows": max(0, int(n - lookback - horizon + 1)),
        })
    return pd.DataFrame(rows).sort_values("city").reset_index(drop=True)


# ============================================================
# Train/evaluate
# ============================================================


def train_one_epoch(
    model,
    loader: DataLoader,
    optimizer,
    horizon_weights: torch.Tensor,
    device: str,
    use_city_embedding: bool,
    grad_clip: float,
    loss_name: str,
    huber_beta: float,
    daylight_weight: float,
    night_weight: float,
    production_weight: float,
    max_kw_per_kwp: float,
) -> float:
    model.train()
    loss_sum = 0.0
    count = 0

    for batch in loader:
        x, city_id, y_scaled, y_raw, daylight = unpack_batch(batch, use_city_embedding)

        x = x.to(device)
        y_scaled = y_scaled.to(device)
        y_raw = y_raw.to(device)
        daylight = daylight.to(device)

        if city_id is not None:
            city_id = city_id.to(device)

        optimizer.zero_grad(set_to_none=True)
        pred_scaled = model(x, city_id) if use_city_embedding else model(x)

        loss = solar_weighted_loss(
            pred_scaled=pred_scaled,
            true_scaled=y_scaled,
            true_raw=y_raw,
            daylight=daylight,
            horizon_weights=horizon_weights,
            loss_name=loss_name,
            huber_beta=huber_beta,
            daylight_weight=daylight_weight,
            night_weight=night_weight,
            production_weight=production_weight,
            max_kw_per_kwp=max_kw_per_kwp,
        )

        loss.backward()
        if grad_clip > 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
        optimizer.step()

        batch_size = x.size(0)
        loss_sum += float(loss.item()) * batch_size
        count += batch_size

    return loss_sum / max(1, count)



@torch.no_grad()
def collect_predictions(
    model,
    loader: DataLoader,
    y_scaler: StandardScaler,
    device: str,
    use_city_embedding: bool,
    clip_per_kwp: bool,
    max_kw_per_kwp: float,
    force_night_zero: bool,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return raw prediction arrays after the standard physical post-processing."""
    model.eval()

    pred_all = []
    true_all = []
    daylight_all = []

    for batch in loader:
        x, city_id, _, y_raw, daylight = unpack_batch(batch, use_city_embedding)

        x = x.to(device)
        if city_id is not None:
            city_id = city_id.to(device)

        pred_scaled = model(x, city_id) if use_city_embedding else model(x)
        pred_scaled_np = pred_scaled.detach().cpu().numpy()
        pred_raw = inverse_scaled(pred_scaled_np, y_scaler)

        daylight_np = daylight.numpy().astype(np.float32)
        pred_raw = final_physical_postprocess(
            pred_raw,
            daylight_np,
            clip_per_kwp=clip_per_kwp,
            max_kw_per_kwp=max_kw_per_kwp,
            force_night_zero=force_night_zero,
        )

        pred_all.append(pred_raw.astype(np.float32))
        true_all.append(y_raw.numpy().astype(np.float32))
        daylight_all.append(daylight_np.astype(np.float32))

    pred = np.concatenate(pred_all, axis=0)
    true = np.concatenate(true_all, axis=0)
    daylight = np.concatenate(daylight_all, axis=0)
    return pred, true, daylight


@torch.no_grad()
def evaluate_model(
    model,
    loader: DataLoader,
    y_scaler: StandardScaler,
    device: str,
    use_city_embedding: bool,
    reference_capacity_kwp: float,
    clip_per_kwp: bool,
    max_kw_per_kwp: float,
    force_night_zero: bool,
) -> Tuple[Dict[str, float], pd.DataFrame]:
    model.eval()

    pred_all = []
    true_all = []
    daylight_all = []

    for batch in loader:
        x, city_id, _, y_raw, daylight = unpack_batch(batch, use_city_embedding)

        x = x.to(device)
        if city_id is not None:
            city_id = city_id.to(device)

        pred_scaled = model(x, city_id) if use_city_embedding else model(x)
        pred_scaled_np = pred_scaled.detach().cpu().numpy()
        pred_raw = inverse_scaled(pred_scaled_np, y_scaler)

        daylight_np = daylight.numpy()
        if force_night_zero:
            pred_raw = np.where(daylight_np > 0.5, pred_raw, 0.0)

        if clip_per_kwp:
            pred_raw = np.clip(pred_raw, 0.0, float(max_kw_per_kwp))

        pred_all.append(pred_raw.astype(np.float32))
        true_all.append(y_raw.numpy().astype(np.float32))
        daylight_all.append(daylight_np.astype(np.float32))

    pred = np.concatenate(pred_all, axis=0)
    true = np.concatenate(true_all, axis=0)
    daylight = np.concatenate(daylight_all, axis=0)

    metrics = compute_all_metrics(pred, true, daylight, reference_capacity_kwp)
    ph = per_horizon_metrics(pred, true, daylight, reference_capacity_kwp)
    return metrics, ph


# ============================================================
# Save utilities
# ============================================================


def save_experiment_config(
    out_dir: str,
    args,
    target_col: str,
    feature_cols: Sequence[str],
    continuous_cols: Sequence[str],
    x_scaler: Optional[StandardScaler],
    y_scaler: StandardScaler,
) -> None:
    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(out_dir, "feature_cols.json"), "w", encoding="utf-8") as f:
        json.dump(list(feature_cols), f, indent=2)

    with open(os.path.join(out_dir, "continuous_cols.json"), "w", encoding="utf-8") as f:
        json.dump(list(continuous_cols), f, indent=2)

    config = vars(args).copy()
    config["resolved_target_col"] = target_col
    config["feature_cols"] = list(feature_cols)
    config["continuous_cols"] = list(continuous_cols)

    with open(os.path.join(out_dir, "config.json"), "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2)

    if x_scaler is not None:
        joblib.dump(x_scaler, os.path.join(out_dir, "x_scaler.pkl"))
    joblib.dump(y_scaler, os.path.join(out_dir, "y_scaler_solar.pkl"))


# ============================================================
# Train one seed
# ============================================================


def train_one_seed(
    train_loader: DataLoader,
    val_loader: DataLoader,
    test_loader: DataLoader,
    n_features: int,
    n_cities: int,
    y_scaler: StandardScaler,
    args,
    device: str,
    seed: int,
    embedding_dim: Optional[int],
    checkpoint_path: Optional[str],
):
    set_seed(seed)
    use_city_embedding = args.mode == "city_embedding"

    if use_city_embedding:
        model = SolarLSTMCityEmbedding(
            n_features=n_features,
            n_cities=n_cities,
            city_embedding_dim=int(embedding_dim),
            hidden_size=args.hidden_size,
            num_layers=args.num_layers,
            dropout=args.dropout,
            horizon=args.horizon,
            head_hidden=args.head_hidden,
        ).to(device)
    else:
        model = SolarLSTM(
            n_features=n_features,
            hidden_size=args.hidden_size,
            num_layers=args.num_layers,
            dropout=args.dropout,
            horizon=args.horizon,
            head_hidden=args.head_hidden,
        ).to(device)

    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"  Model parameters: {n_params:,}")

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=args.lr_factor,
        patience=args.lr_patience,
    )

    horizon_weights = build_horizon_weights(args.horizon, device)
    early = EarlyStopping(patience=args.early_patience, min_delta=args.min_delta)

    best_state = None
    best_epoch = 0
    best_val_metric = float("inf")

    for epoch in range(1, args.epochs + 1):
        train_loss = train_one_epoch(
            model=model,
            loader=train_loader,
            optimizer=optimizer,
            horizon_weights=horizon_weights,
            device=device,
            use_city_embedding=use_city_embedding,
            grad_clip=args.grad_clip,
            loss_name=args.loss,
            huber_beta=args.huber_beta,
            daylight_weight=args.active_daylight_weight,
            night_weight=args.night_weight,
            production_weight=args.active_production_weight,
            max_kw_per_kwp=args.max_kw_per_kwp,
        )

        val_metrics, _ = evaluate_model(
            model=model,
            loader=val_loader,
            y_scaler=y_scaler,
            device=device,
            use_city_embedding=use_city_embedding,
            reference_capacity_kwp=args.reference_capacity_kwp,
            clip_per_kwp=args.clip_per_kwp,
            max_kw_per_kwp=args.max_kw_per_kwp,
            force_night_zero=args.force_night_zero,
        )

        if args.monitor_metric not in val_metrics:
            raise ValueError(f"Monitor metric not available: {args.monitor_metric}")
        monitor_metric = val_metrics[args.monitor_metric]
        scheduler.step(monitor_metric)
        stop, improved = early.step(monitor_metric)

        if improved:
            best_state = copy.deepcopy(model.state_dict())
            best_epoch = epoch
            best_val_metric = monitor_metric

        if args.verbose:
            print(
                f"  epoch={epoch:03d} | train_loss={train_loss:.6f} | "
                f"val_per_kwp_RMSE={val_metrics['per_kwp_rmse']:.6f} | "
                f"val_daylight_RMSE={val_metrics.get('daylight_per_kwp_rmse', float('nan')):.6f} | "
                f"val_ref_RMSE={val_metrics['reference_kw_rmse']:.2f} kW | "
                f"val_R2={val_metrics['per_kwp_r2']:.4f}"
            )

        if stop:
            print(f"  Early stop at epoch {epoch}.")
            break

    if best_state is None:
        best_state = copy.deepcopy(model.state_dict())

    model.load_state_dict(best_state)

    if checkpoint_path is not None:
        torch.save(best_state, checkpoint_path)

    # v3: fit transparent post-processing correction on validation only,
    # then apply the selected correction to test.
    val_pred, val_true, val_daylight = collect_predictions(
        model=model,
        loader=val_loader,
        y_scaler=y_scaler,
        device=device,
        use_city_embedding=use_city_embedding,
        clip_per_kwp=args.clip_per_kwp,
        max_kw_per_kwp=args.max_kw_per_kwp,
        force_night_zero=args.force_night_zero,
    )
    test_pred, test_true, test_daylight = collect_predictions(
        model=model,
        loader=test_loader,
        y_scaler=y_scaler,
        device=device,
        use_city_embedding=use_city_embedding,
        clip_per_kwp=args.clip_per_kwp,
        max_kw_per_kwp=args.max_kw_per_kwp,
        force_night_zero=args.force_night_zero,
    )

    correction_params, calibration_df = choose_validation_correction(
        val_pred=val_pred,
        val_true=val_true,
        val_daylight=val_daylight,
        correction_methods=args.bias_corrections,
        selection_metric=args.calibration_metric,
        reference_capacity_kwp=args.reference_capacity_kwp,
        clip_per_kwp=args.clip_per_kwp,
        max_kw_per_kwp=args.max_kw_per_kwp,
        force_night_zero=args.force_night_zero,
    )

    corrected_test_pred = apply_bias_correction(test_pred, test_daylight, correction_params)
    corrected_test_pred = final_physical_postprocess(
        corrected_test_pred,
        test_daylight,
        clip_per_kwp=args.clip_per_kwp,
        max_kw_per_kwp=args.max_kw_per_kwp,
        force_night_zero=args.force_night_zero,
    )

    test_metrics = compute_all_metrics(
        corrected_test_pred,
        test_true,
        test_daylight,
        args.reference_capacity_kwp,
    )
    per_horizon = per_horizon_metrics(
        corrected_test_pred,
        test_true,
        test_daylight,
        args.reference_capacity_kwp,
    )

    correction_method = str(correction_params.get("method", "none"))
    test_metrics["selected_correction_method"] = correction_method
    test_metrics["selected_correction_selection_metric"] = args.calibration_metric
    test_metrics["selected_correction_val_score"] = float(calibration_df.iloc[0]["selection_score"]) if len(calibration_df) else float("nan")

    return test_metrics, per_horizon, best_epoch, best_val_metric, calibration_df, correction_params


# ============================================================
# Main experiment
# ============================================================


def run_experiment(args) -> None:
    os.makedirs(args.out_dir, exist_ok=True)

    print("=" * 120)
    print("LOADING DATA")
    print("=" * 120)

    train_df, train_target_col = load_split(args.train_data, "train", args.target_col)
    val_df, val_target_col = load_split(args.val_data, "valid", args.target_col)
    test_df, test_target_col = load_split(args.test_data, "test", args.target_col)

    if not (train_target_col == val_target_col == test_target_col):
        raise ValueError(
            f"Target mismatch: train={train_target_col}, valid={val_target_col}, test={test_target_col}"
        )
    target_col = train_target_col

    check_split_integrity(train_df, val_df, test_df)

    # Keep only common columns across splits.
    common_cols = sorted(set(train_df.columns) & set(val_df.columns) & set(test_df.columns))
    train_df = train_df[common_cols].copy()
    val_df = val_df[common_cols].copy()
    test_df = test_df[common_cols].copy()

    train_df = prepare_physical_target(train_df, target_col)
    val_df = prepare_physical_target(val_df, target_col)
    test_df = prepare_physical_target(test_df, target_col)

    use_solar_history = not args.no_solar_history
    if use_solar_history:
        print("Building past-only solar AR features...")
        train_df = add_ar_solar_features(train_df, target_col)
        val_df = add_ar_solar_features(val_df, target_col)
        test_df = add_ar_solar_features(test_df, target_col)

    feature_cols, continuous_cols = build_feature_columns(
        train_df,
        feature_set=args.feature_set,
        use_solar_history=use_solar_history,
    )

    required_cols = feature_cols + [TARGET_VALUE_COL, RAW_TARGET_COL, DAYLIGHT_COL]
    for name, df in [("train", train_df), ("valid", val_df), ("test", test_df)]:
        before = len(df)
        df.dropna(subset=required_cols, inplace=True)
        after = len(df)
        if before != after:
            print(f"  {name}: dropped {before - after:,} rows with NaNs.")

    train_df, val_df, test_df, x_scaler, y_scaler = fit_apply_scalers(
        train_df=train_df,
        val_df=val_df,
        test_df=test_df,
        feature_cols=feature_cols,
        continuous_cols=continuous_cols,
    )

    save_experiment_config(
        out_dir=args.out_dir,
        args=args,
        target_col=target_col,
        feature_cols=feature_cols,
        continuous_cols=continuous_cols,
        x_scaler=x_scaler,
        y_scaler=y_scaler,
    )

    device = "cuda" if torch.cuda.is_available() else "cpu"
    use_city_embedding = args.mode == "city_embedding"

    n_cities = int(
        max(train_df["city_id"].max(), val_df["city_id"].max(), test_df["city_id"].max())
    ) + 1

    print("=" * 120)
    print("SOLAR LSTM PV-PER-KWP v3")
    print("=" * 120)
    print(f"Device              : {device}")
    print(f"Mode                : {args.mode}")
    print(f"Feature set         : {args.feature_set}")
    print(f"Target column       : {target_col}")
    print(f"Solar history       : {use_solar_history}")
    print(f"Lookbacks           : {args.lookbacks}")
    print(f"Horizon             : {args.horizon}")
    print(f"Reference capacity  : {args.reference_capacity_kwp:.3f} kWp")
    print(f"Force night zero    : {args.force_night_zero}")
    print(f"Clip per-kWp output : {args.clip_per_kwp} [0, {args.max_kw_per_kwp}]")
    print(f"N cities            : {n_cities}")
    print(f"N features          : {len(feature_cols)}")
    print(f"Loss                : {args.loss} + daylight/production/horizon weights")
    print(f"Monitor metric      : {args.monitor_metric}")
    print(f"Daylight weights    : {args.daylight_weights}")
    print(f"Night weight        : {args.night_weight}")
    print(f"Production weights  : {args.production_weights}")
    print(f"Bias corrections    : {args.bias_corrections}")
    print(f"Calibration metric  : {args.calibration_metric}")
    if args.feature_set == "physics":
        print("WARNING: physics feature set includes PV intermediate columns such as POA and cell temperature.")
        print("Use this only for a PV-emulator or NASA-aligned experiment, not a strict no-leakage forecast.")
    print("Features:")
    for c in feature_cols:
        print(f"  {c}")

    summary_rows = []
    embedding_dims = args.embedding_dims if use_city_embedding else [None]

    for daylight_weight in args.daylight_weights:
        for production_weight in args.production_weights:
            args.active_daylight_weight = float(daylight_weight)
            args.active_production_weight = float(production_weight)
            weight_tag = (
                f"_dw{float_tag(daylight_weight)}"
                f"_nw{float_tag(args.night_weight)}"
                f"_pw{float_tag(production_weight)}"
            )

            for embedding_dim in embedding_dims:
                for lookback in args.lookbacks:
                    if lookback <= 0:
                        raise ValueError(f"lookback must be positive, got {lookback}")
                    if lookback < args.horizon:
                        print(
                            f"\n[INFO] lookback={lookback} < horizon={args.horizon}; "
                            "running as a valid direct multi-output configuration."
                        )

                    print("\n" + "-" * 100)
                    print(
                        f"lookback={lookback} | horizon={args.horizon} | "
                        f"embedding_dim={embedding_dim} | daylight_weight={daylight_weight} | "
                        f"night_weight={args.night_weight} | production_weight={production_weight}"
                    )
                    print("-" * 100)

                    count_windows(train_df, lookback, args.horizon).to_csv(
                        os.path.join(args.out_dir, f"window_counts_train{weight_tag}_L{lookback}_H{args.horizon}.csv"),
                        index=False,
                    )

                    train_ds = SolarPVPerKwpDataset(train_df, feature_cols, lookback, args.horizon, use_city_embedding)
                    val_ds = SolarPVPerKwpDataset(val_df, feature_cols, lookback, args.horizon, use_city_embedding)
                    test_ds = SolarPVPerKwpDataset(test_df, feature_cols, lookback, args.horizon, use_city_embedding)

                    if len(train_ds) == 0 or len(val_ds) == 0 or len(test_ds) == 0:
                        print("  Skipping: not enough windows.")
                        continue

                    print(f"  Windows: train={len(train_ds):,}  valid={len(val_ds):,}  test={len(test_ds):,}")

                    train_loader = make_loader(train_ds, args, shuffle=True, device=device)
                    val_loader = make_loader(val_ds, args, shuffle=False, device=device)
                    test_loader = make_loader(test_ds, args, shuffle=False, device=device)

                    seed_rows = []
                    horizon_rows = []
                    calibration_rows = []

                    for seed in args.seeds:
                        print(f"\n  Seed: {seed}")

                        checkpoint_path = None
                        if args.save_models:
                            ckpt_dir = os.path.join(args.out_dir, "checkpoints")
                            os.makedirs(ckpt_dir, exist_ok=True)
                            emb_tag = f"_emb{embedding_dim}" if embedding_dim is not None else ""
                            checkpoint_path = os.path.join(
                                ckpt_dir,
                                f"solar_pv_per_kwp{weight_tag}{emb_tag}_L{lookback}_H{args.horizon}_seed{seed}.pt",
                            )

                        metrics, ph, best_epoch, best_val, cal_df, correction_params = train_one_seed(
                            train_loader=train_loader,
                            val_loader=val_loader,
                            test_loader=test_loader,
                            n_features=len(feature_cols),
                            n_cities=n_cities,
                            y_scaler=y_scaler,
                            args=args,
                            device=device,
                            seed=seed,
                            embedding_dim=embedding_dim,
                            checkpoint_path=checkpoint_path,
                        )

                        row = {
                            "path_type": "solar_lstm_pv_per_kwp_v3",
                            "mode": args.mode,
                            "feature_set": args.feature_set,
                            "embedding_dim": embedding_dim,
                            "lookback": lookback,
                            "horizon": args.horizon,
                            "daylight_weight": float(daylight_weight),
                            "night_weight": float(args.night_weight),
                            "production_weight": float(production_weight),
                            "monitor_metric": args.monitor_metric,
                            "seed": seed,
                            "best_epoch": best_epoch,
                            "best_val_metric": best_val,
                            "selected_correction_method": metrics.get("selected_correction_method", "none"),
                            "selected_correction_val_score": metrics.get("selected_correction_val_score", float("nan")),
                            **{f"test_{k}": v for k, v in metrics.items()},
                        }
                        seed_rows.append(row)

                        cal_df.insert(0, "seed", seed)
                        cal_df.insert(0, "production_weight", float(production_weight))
                        cal_df.insert(0, "night_weight", float(args.night_weight))
                        cal_df.insert(0, "daylight_weight", float(daylight_weight))
                        cal_df.insert(0, "lookback", lookback)
                        cal_df.insert(0, "embedding_dim", embedding_dim)
                        cal_df.insert(0, "mode", args.mode)
                        calibration_rows.append(cal_df)

                        ph.insert(0, "seed", seed)
                        ph.insert(0, "production_weight", float(production_weight))
                        ph.insert(0, "night_weight", float(args.night_weight))
                        ph.insert(0, "daylight_weight", float(daylight_weight))
                        ph.insert(0, "lookback", lookback)
                        ph.insert(0, "embedding_dim", embedding_dim)
                        ph.insert(0, "mode", args.mode)
                        horizon_rows.append(ph)

                        print(
                            f"  seed={seed} | "
                            f"per_kWp_RMSE={metrics['per_kwp_rmse']:.6f} | "
                            f"daylight_RMSE={metrics.get('daylight_per_kwp_rmse', float('nan')):.6f} | "
                            f"ref_RMSE={metrics['reference_kw_rmse']:.2f} kW | "
                            f"bias={metrics['bias_pct_of_reference_capacity']:.3f}% | "
                            f"corr={metrics.get('selected_correction_method', 'none')} | "
                            f"R2={metrics['per_kwp_r2']:.4f} | "
                            f"best_epoch={best_epoch}"
                        )

                    seed_df = pd.DataFrame(seed_rows)
                    horizon_df = pd.concat(horizon_rows, ignore_index=True)
                    calibration_df = pd.concat(calibration_rows, ignore_index=True) if calibration_rows else pd.DataFrame()

                    emb_tag = f"_emb{embedding_dim}" if embedding_dim is not None else ""
                    seed_csv = os.path.join(
                        args.out_dir,
                        f"solar_pv_per_kwp{weight_tag}{emb_tag}_L{lookback}_H{args.horizon}_seeds.csv",
                    )
                    horizon_csv = os.path.join(
                        args.out_dir,
                        f"solar_pv_per_kwp{weight_tag}{emb_tag}_L{lookback}_H{args.horizon}_per_horizon.csv",
                    )
                    calibration_csv = os.path.join(
                        args.out_dir,
                        f"solar_pv_per_kwp{weight_tag}{emb_tag}_L{lookback}_H{args.horizon}_calibration.csv",
                    )

                    seed_df.to_csv(seed_csv, index=False)
                    horizon_df.to_csv(horizon_csv, index=False)
                    calibration_df.to_csv(calibration_csv, index=False)

                    summary_rows.append({
                        "path_type": "solar_lstm_pv_per_kwp_v3",
                        "mode": args.mode,
                        "feature_set": args.feature_set,
                        "embedding_dim": embedding_dim,
                        "lookback": lookback,
                        "horizon": args.horizon,
                        "daylight_weight": float(daylight_weight),
                        "night_weight": float(args.night_weight),
                        "production_weight": float(production_weight),
                        "monitor_metric": args.monitor_metric,
                        "calibration_metric": args.calibration_metric,
                        "selected_correction_methods": ",".join(sorted(seed_df["selected_correction_method"].astype(str).unique().tolist())),
                        "per_kwp_rmse_mean": float(seed_df["test_per_kwp_rmse"].mean()),
                        "per_kwp_rmse_std": float(seed_df["test_per_kwp_rmse"].std(ddof=0)),
                        "per_kwp_mae_mean": float(seed_df["test_per_kwp_mae"].mean()),
                        "per_kwp_mae_std": float(seed_df["test_per_kwp_mae"].std(ddof=0)),
                        "per_kwp_r2_mean": float(seed_df["test_per_kwp_r2"].mean()),
                        "per_kwp_r2_std": float(seed_df["test_per_kwp_r2"].std(ddof=0)),
                        "daylight_per_kwp_rmse_mean": float(seed_df.get("test_daylight_per_kwp_rmse", pd.Series(dtype=float)).mean()),
                        "daylight_per_kwp_mae_mean": float(seed_df.get("test_daylight_per_kwp_mae", pd.Series(dtype=float)).mean()),
                        "daylight_per_kwp_r2_mean": float(seed_df.get("test_daylight_per_kwp_r2", pd.Series(dtype=float)).mean()),
                        "reference_kw_rmse_mean": float(seed_df["test_reference_kw_rmse"].mean()),
                        "reference_kw_mae_mean": float(seed_df["test_reference_kw_mae"].mean()),
                        "rmse_pct_capacity_mean": float(seed_df["test_rmse_pct_of_reference_capacity"].mean()),
                        "mae_pct_capacity_mean": float(seed_df["test_mae_pct_of_reference_capacity"].mean()),
                        "bias_pct_capacity_mean": float(seed_df["test_bias_pct_of_reference_capacity"].mean()),
                        "mean_true_cf_pct": float(seed_df["test_mean_true_capacity_factor_pct"].mean()),
                        "mean_pred_cf_pct": float(seed_df["test_mean_pred_capacity_factor_pct"].mean()),
                        "best_seed_by_overall_rmse": int(seed_df.sort_values("test_per_kwp_rmse").iloc[0]["seed"]),
                        "best_seed_by_daylight_rmse": int(seed_df.sort_values("test_daylight_per_kwp_rmse").iloc[0]["seed"]) if "test_daylight_per_kwp_rmse" in seed_df.columns else int(seed_df.sort_values("test_per_kwp_rmse").iloc[0]["seed"]),
                        "seed_csv": seed_csv,
                        "per_horizon_csv": horizon_csv,
                        "calibration_csv": calibration_csv,
                    })

    summary_df = pd.DataFrame(summary_rows)
    if len(summary_df) > 0:
        sort_col = "daylight_per_kwp_rmse_mean" if "daylight_per_kwp_rmse_mean" in summary_df.columns else "per_kwp_rmse_mean"
        summary_df = summary_df.sort_values(sort_col).reset_index(drop=True)

    summary_csv = os.path.join(args.out_dir, "solar_pv_per_kwp_summary.csv")
    best_csv = os.path.join(args.out_dir, "solar_pv_per_kwp_best_config.csv")

    summary_df.to_csv(summary_csv, index=False)
    if len(summary_df) > 0:
        summary_df.head(1).to_csv(best_csv, index=False)

    print("\n" + "=" * 120)
    print("EXPERIMENT COMPLETE")
    print("=" * 120)
    print(f"Summary    : {summary_csv}")
    print(f"Best config: {best_csv}")

    if len(summary_df) > 0:
        cols = [
            "mode", "feature_set", "embedding_dim", "lookback", "horizon",
            "daylight_weight", "night_weight", "production_weight", "selected_correction_methods",
            "daylight_per_kwp_rmse_mean", "per_kwp_rmse_mean", "per_kwp_mae_mean", "per_kwp_r2_mean",
            "reference_kw_rmse_mean", "rmse_pct_capacity_mean", "mean_true_cf_pct",
        ]
        cols = [c for c in cols if c in summary_df.columns]
        print("\nTop results:")
        print(summary_df[cols].head(20).to_string(index=False))

    print("=" * 120)


# ============================================================
# Arguments
# ============================================================


def parse_args():
    parser = argparse.ArgumentParser(
        description="Solar-only LSTM forecasting PV AC power per kWp — v3 with validation-fitted bias correction"
    )

    parser.add_argument("--train_data", type=str, default="/workspace/lstm/data2/train.csv")
    parser.add_argument("--val_data", type=str, default="/workspace/lstm/data2/valid.csv")
    parser.add_argument("--test_data", type=str, default="/workspace/lstm/data2/test.csv")

    parser.add_argument(
        "--target_col",
        type=str,
        default="auto",
        help="Use 'auto' to prefer target_solar_power_kw_per_kwp, then pv_ac_power_kw_per_kwp.",
    )

    parser.add_argument(
        "--mode",
        type=str,
        default="global",
        choices=["global", "city_embedding"],
    )

    parser.add_argument(
        "--feature_set",
        type=str,
        default="basic",
        choices=["basic", "physics"],
        help="basic avoids PV intermediate columns; physics adds pv_poa_global_wm2 and pv_cell_temperature_c.",
    )

    parser.add_argument(
        "--lookbacks",
        nargs="+",
        type=int,
        default=DEFAULT_LOOKBACKS,
        help="Candidate input-window lengths in hours. Shorter-than-horizon windows are allowed for direct multi-output forecasting.",
    )
    parser.add_argument("--horizon", type=int, default=6)

    parser.add_argument(
        "--embedding_dims",
        nargs="+",
        type=int,
        default=DEFAULT_EMBEDDING_DIMS,
    )

    parser.add_argument(
        "--no_solar_history",
        action="store_true",
        help="Disable past-only solar lag/rolling features.",
    )

    parser.add_argument("--epochs", type=int, default=150)
    parser.add_argument("--batch_size", type=int, default=512)
    parser.add_argument("--hidden_size", type=int, default=256)
    parser.add_argument("--num_layers", type=int, default=3)
    parser.add_argument("--dropout", type=float, default=0.2)
    parser.add_argument("--head_hidden", type=int, default=128)

    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument("--grad_clip", type=float, default=1.0)

    parser.add_argument(
        "--loss",
        type=str,
        default="huber",
        choices=["huber", "mse", "mae"],
    )
    parser.add_argument("--huber_beta", type=float, default=1.0)
    parser.add_argument(
        "--daylight_weights",
        nargs="+",
        type=float,
        default=DEFAULT_DAYLIGHT_WEIGHTS,
        help="Grid of daylight weights to try. Daylight hours get this weight in the loss.",
    )
    parser.add_argument(
        "--night_weight",
        type=float,
        default=0.25,
        help="Weight for night samples in the loss. Lower values reduce domination by night zeros.",
    )
    parser.add_argument(
        "--production_weights",
        nargs="+",
        type=float,
        default=DEFAULT_PRODUCTION_WEIGHTS,
        help="Grid of production-intensity weights to try.",
    )
    parser.add_argument(
        "--monitor_metric",
        type=str,
        default="daylight_per_kwp_rmse",
        choices=["per_kwp_rmse", "daylight_per_kwp_rmse", "reference_kw_rmse"],
        help="Validation metric used for LR scheduling and early stopping.",
    )
    parser.add_argument(
        "--bias_corrections",
        nargs="+",
        type=str,
        default=DEFAULT_BIAS_CORRECTIONS,
        help=(
            "Post-processing corrections to try on the validation split. "
            "Allowed: none, global_bias, daylight_bias, horizon_bias, horizon_daylight_bias, linear."
        ),
    )
    parser.add_argument(
        "--calibration_metric",
        type=str,
        default="daylight_per_kwp_rmse",
        choices=[
            "per_kwp_rmse",
            "per_kwp_mae",
            "daylight_per_kwp_rmse",
            "daylight_per_kwp_mae",
            "reference_kw_rmse",
            "abs_bias_pct_of_reference_capacity",
        ],
        help="Validation metric used to select the post-processing correction for each seed.",
    )

    parser.add_argument("--early_patience", type=int, default=15)
    parser.add_argument("--min_delta", type=float, default=1e-5)
    parser.add_argument("--lr_patience", type=int, default=5)
    parser.add_argument("--lr_factor", type=float, default=0.5)

    parser.add_argument(
        "--seeds",
        nargs="+",
        type=int,
        default=DEFAULT_SEEDS,
    )

    parser.add_argument("--reference_capacity_kwp", type=float, default=DEFAULT_REFERENCE_CAPACITY_KWP)
    parser.add_argument("--max_kw_per_kwp", type=float, default=DEFAULT_MAX_KW_PER_KWP)
    parser.add_argument("--num_workers", type=int, default=2)

    parser.add_argument(
        "--no_clip_per_kwp",
        action="store_true",
        help="Disable clipping predictions to [0, max_kw_per_kwp].",
    )
    parser.add_argument(
        "--no_force_night_zero",
        action="store_true",
        help="Disable physically forcing predictions to zero when is_daylight=0.",
    )

    parser.add_argument("--save_models", action="store_true")
    parser.add_argument("--verbose", action="store_true")

    parser.add_argument(
        "--out_dir",
        type=str,
        default="/workspace/lstm/output/solar_lstm_pv_per_kwp_v3",
    )

    args = parser.parse_args()
    args.clip_per_kwp = not args.no_clip_per_kwp
    args.force_night_zero = not args.no_force_night_zero
    allowed_corrections = {"none", "global_bias", "daylight_bias", "horizon_bias", "horizon_daylight_bias", "linear"}
    bad = [m for m in args.bias_corrections if m not in allowed_corrections]
    if bad:
        raise ValueError(f"Unknown bias correction methods: {bad}. Allowed: {sorted(allowed_corrections)}")

    return args


def main():
    args = parse_args()
    run_experiment(args)


if __name__ == "__main__":
    main()
